import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
test("CasaOS package has required files",async()=>{const compose=await readFile("docker-compose.yml","utf8");const env=await readFile(".env.example","utf8");assert.match(compose,/ainet-approval/);assert.match(compose,/8093/);assert.match(env,/ADMIN_PASSWORD/);assert.match(env,/APP_ACCESS_PASSWORD/);assert.match(compose,/APP_ACCESS_PASSWORD/)});

test("global access gate protects app routes",async()=>{const proxy=await readFile("proxy.ts","utf8");const access=await readFile("lib/access-gate.ts","utf8");assert.match(access,/ainet_access/);assert.match(proxy,/\/api\/access/);assert.match(proxy,/\/health/);assert.match(proxy,/Password akses awal diperlukan/)});

test("super admin can manage access password and branding",async()=>{const settings=await readFile("components/AdminSettings.tsx","utf8");const accessRoute=await readFile("app/api/admin/access-password/route.ts","utf8");const schema=await readFile("db/runtime.ts","utf8");assert.match(settings,/Password masuk/);assert.match(settings,/Identitas aplikasi/);assert.match(settings,/👁/);assert.match(accessRoute,/\[A-Za-z0-9\]/);assert.match(accessRoute,/super_admin/);assert.match(schema,/app_settings/)});

test("tracking view exposes complete protected submission detail",async()=>{const route=await readFile("app/api/tracking/route.ts","utf8");const fileRoute=await readFile("app/api/tracking/file/route.ts","utf8");const panel=await readFile("components/TrackingPanel.tsx","utf8");assert.match(route,/requester_phone AS requesterPhone/);assert.match(route,/description/);assert.match(route,/FROM documents/);assert.match(route,/approver_name AS approverName/);assert.match(fileRoute,/verifyPassword/);assert.match(fileRoute,/submission_id = \?/);assert.match(panel,/Identitas pemohon/);assert.match(panel,/Isi pengajuan/);assert.match(panel,/Lampiran pengajuan/);assert.match(panel,/Progres persetujuan/)});

test("branding supports color palettes",async()=>{const config=await readFile("lib/branding-config.ts","utf8");const provider=await readFile("components/BrandingProvider.tsx","utf8");const settings=await readFile("components/AdminSettings.tsx","utf8");assert.match(config,/primaryColor/);assert.match(config,/headerTextColor/);assert.match(provider,/--title-color/);assert.match(settings,/Palet warna/);assert.match(settings,/type="color"/)});
