"use client";

import { FormEvent, useEffect, useState } from "react";

type User = { id:string; email:string; username:string; name:string; role:string; jobTitle:string; department:string; active:number; hasPassword:number; hasSignature:number };
type FormType = { id:string; name:string; description:string; requiresAmount:number; active:number };
type Option = { id:string; kind:string; label:string; sortOrder:number; active:number };
type Data = { users:User[]; formTypes:FormType[]; options:Option[]; currentUser:{role:string} };

export default function AdminSettings(){
  const [data,setData]=useState<Data|null>(null); const [tab,setTab]=useState<"form"|"users"|"master">("form");
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [editingForm,setEditingForm]=useState<FormType|null>(null); const [editingUser,setEditingUser]=useState<User|null>(null);
  function load(){fetch("/api/admin/settings").then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}).catch(e=>setMessage(e.message));}
  useEffect(load,[]);
  async function send(payload:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error);await load();setEditingForm(null);setEditingUser(null);}catch(e){setMessage(e instanceof Error?e.message:"Data belum dapat disimpan.")}finally{setBusy(false)}}
  function saveForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);send({action:editingForm?"edit_form_type":"add_form_type",id:editingForm?.id,name:f.get("name"),description:f.get("description"),requiresAmount:f.get("requiresAmount")==="on"});if(!editingForm)e.currentTarget.reset();}
  function saveUser(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);send({action:"add_user",name:f.get("name"),username:f.get("username"),email:f.get("email"),role:f.get("role"),jobTitle:f.get("jobTitle"),department:f.get("department"),password:f.get("password")});if(!editingUser)e.currentTarget.reset();}
  function saveOption(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);send({action:"save_option",kind:f.get("kind"),label:f.get("label"),sortOrder:f.get("sortOrder")});e.currentTarget.reset();}
  const superAdmin=data?.currentUser.role==="super_admin";
  return <div className="admin-page settings-page"><div className="admin-topline"><div><span className="eyebrow">Administrasi</span><h1>Pengaturan aplikasi</h1><p>Kelola formulir, pilihan data, serta akun Super Admin, Admin, dan Approval.</p></div></div>
    {message&&<p className="form-error inline-error">{message}</p>}
    <div className="settings-tabs"><button className={tab==="form"?"active":""} onClick={()=>setTab("form")}>Jenis formulir</button><button className={tab==="master"?"active":""} onClick={()=>setTab("master")}>Jabatan & divisi</button><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}>Pengguna & akses</button></div>
    {!data?<div className="admin-loading"><span/><span/><span/></div>:tab==="form"?<div className="settings-layout">
      <section className="admin-card settings-list"><div className="card-heading"><div><b>Formulir publik</b><small>Edit atau aktifkan formulir yang tersedia bagi pemohon</small></div></div>{data.formTypes.map(item=><div className="setting-row" key={item.id}><span>FM</span><div><b>{item.name}</b><small>{item.description}</small></div><em className={item.active?"on":"off"}>{item.active?"Aktif":"Nonaktif"}</em><div className="setting-actions"><button onClick={()=>setEditingForm(item)}>Edit</button><button disabled={busy} onClick={()=>send({action:"toggle_form_type",id:item.id})}>{item.active?"Nonaktifkan":"Aktifkan"}</button></div></div>)}</section>
      <section className="admin-card settings-form"><div className="card-heading"><div><b>{editingForm?"Edit formulir":"Tambah formulir"}</b><small>{editingForm?"Perubahan berlaku pada pengajuan berikutnya":"Form baru langsung tersedia di halaman publik"}</small></div></div><form key={editingForm?.id||"new"} onSubmit={saveForm}><label>Nama formulir<input name="name" required defaultValue={editingForm?.name||""} placeholder="Contoh: Permohonan Cuti"/></label><label>Deskripsi<textarea name="description" rows={4} required defaultValue={editingForm?.description||""}/></label><label className="setting-check"><input type="checkbox" name="requiresAmount" defaultChecked={!!editingForm?.requiresAmount}/><span>Nominal wajib diisi</span></label><button disabled={busy} className="button primary">{editingForm?"Simpan perubahan":"Simpan formulir"}</button>{editingForm&&<button type="button" className="text-button" onClick={()=>setEditingForm(null)}>Batal mengedit</button>}</form></section>
    </div>:tab==="master"?<div className="settings-layout">
      <section className="admin-card settings-list"><div className="card-heading"><div><b>Pilihan jabatan & divisi</b><small>Pemohon tetap dapat memilih “Lainnya” dan mengisi manual</small></div></div>{data.options.map(item=><div className="setting-row" key={item.id}><span>{item.kind==="job_title"?"JB":"DV"}</span><div><b>{item.label}</b><small>{item.kind==="job_title"?"Jabatan":"Divisi / PoP"}</small></div><em className={item.active?"on":"off"}>{item.active?"Aktif":"Nonaktif"}</em><button disabled={busy} onClick={()=>send({action:"toggle_option",id:item.id})}>{item.active?"Nonaktifkan":"Aktifkan"}</button></div>)}</section>
      <section className="admin-card settings-form"><div className="card-heading"><div><b>Tambah pilihan</b><small>Atur daftar dropdown pada formulir publik</small></div></div><form onSubmit={saveOption}><label>Jenis<select name="kind"><option value="job_title">Jabatan</option><option value="division">Divisi / PoP</option></select></label><label>Nama pilihan<input name="label" required placeholder="Contoh: Manager Teknis"/></label><label>Urutan<input name="sortOrder" type="number" defaultValue="50"/></label><button disabled={busy} className="button primary">Simpan pilihan</button></form></section>
    </div>:<div className="settings-layout">
      <section className="admin-card settings-list"><div className="card-heading"><div><b>Pengguna internal</b><small>Password approval dibuat satu kali untuk setiap pejabat</small></div></div>{data.users.map(item=><div className="setting-row user-row" key={item.id}><span>{item.name.split(/\s+/).slice(0,2).map(x=>x[0]).join("")}</span><div><b>{item.name}</b><small>{item.email} • {item.jobTitle||item.role} • {item.hasPassword?"password siap":"password belum dibuat"} • {item.hasSignature?"tanda tangan tersimpan":"belum ada tanda tangan"}</small></div><em className={item.active?"on":"off"}>{item.active?"Aktif":"Nonaktif"}</em>{superAdmin&&<div className="setting-actions"><button onClick={()=>setEditingUser(item)}>Edit</button><button disabled={busy} onClick={()=>send({action:"toggle_user",email:item.email})}>{item.active?"Nonaktifkan":"Aktifkan"}</button></div>}</div>)}</section>
      <section className="admin-card settings-form"><div className="card-heading"><div><b>{editingUser?"Edit pengguna":"Tambah pengguna"}</b><small>{superAdmin?"Password yang sama dipakai untuk login dan tautan approval":"Hanya Super Admin yang dapat mengubah pengguna"}</small></div></div>{superAdmin?<form key={editingUser?.id||"new-user"} onSubmit={saveUser}><label>Nama lengkap<input name="name" required defaultValue={editingUser?.name||""}/></label><div className="form-grid"><label>Username<input name="username" required defaultValue={editingUser?.username||""}/></label><label>Email akun<input name="email" type="email" required readOnly={!!editingUser} defaultValue={editingUser?.email||""}/></label></div><div className="form-grid"><label>Jabatan<input name="jobTitle" required defaultValue={editingUser?.jobTitle||""}/></label><label>Divisi<input name="department" defaultValue={editingUser?.department||""}/></label></div><label>Hak akses<select name="role" defaultValue={editingUser?.role||"approver"}><option value="approver">Approval</option><option value="admin">Admin / HRGA</option><option value="super_admin">Super Admin</option></select></label><label>Password akun / approval<input name="password" type="password" minLength={4} required={!editingUser?.hasPassword} placeholder={editingUser?.hasPassword?"Kosongkan jika tidak diubah":"Minimal 4 karakter"}/></label><button disabled={busy} className="button primary">Simpan pengguna</button>{editingUser&&<button type="button" className="text-button" onClick={()=>setEditingUser(null)}>Batal mengedit</button>}</form>:<div className="mini-empty">Masuk sebagai Super Admin untuk mengelola pengguna.</div>}</section>
    </div>}
  </div>
}
