import { ensureSchema,getBucket,getD1,writeAudit } from "@/db/runtime";
import { hashSecret,maskName,verifyPassword } from "@/lib/security";

type ApprovalAccess={id:string;submissionId:string;stepNumber:number;approverEmail:string;approverName:string;approverTitle:string;status:string;linkEnabled:number;submissionStatus:string;currentStep:number;number:string;title:string;requesterName:string;requesterUnit:string;formTypeName:string;createdAt:string;passwordHash:string;storedSignatureKey:string|null};
async function access(token:string){const tokenHash=await hashSecret(token,"approval-link");return getD1().prepare(`SELECT a.id,a.submission_id AS submissionId,a.step_number AS stepNumber,
  a.approver_email AS approverEmail,a.approver_name AS approverName,a.approver_title AS approverTitle,
  a.status,a.link_enabled AS linkEnabled,s.status AS submissionStatus,s.current_step AS currentStep,
  s.number,s.title,s.requester_name AS requesterName,s.requester_unit AS requesterUnit,
  s.form_type_name AS formTypeName,s.created_at AS createdAt,u.approval_password_hash AS passwordHash,
  u.signature_key AS storedSignatureKey FROM approvals a JOIN submissions s ON s.id=a.submission_id
  JOIN users u ON lower(u.email)=lower(a.approver_email) WHERE a.link_token_hash=? AND s.deleted_at IS NULL`).bind(tokenHash).first<ApprovalAccess>()}

export async function GET(_:Request,{params}:{params:Promise<{token:string}>}){await ensureSchema();const {token}=await params;const row=await access(token);if(!row||!row.linkEnabled)return Response.json({error:"Tautan approval tidak aktif."},{status:404});if(row.stepNumber!==row.currentStep||row.status!=="menunggu")return Response.json({error:"Tahap approval ini belum aktif atau sudah selesai."},{status:409});return Response.json({approval:{approverName:row.approverName,approverTitle:row.approverTitle,stepNumber:row.stepNumber,hasStoredSignature:!!row.storedSignatureKey},submission:{number:row.number,title:row.title,requesterName:maskName(row.requesterName),requesterUnit:row.requesterUnit,formTypeName:row.formTypeName,createdAt:row.createdAt}})}

export async function POST(request:Request,{params}:{params:Promise<{token:string}>}){await ensureSchema();const {token}=await params;const row=await access(token);if(!row||!row.linkEnabled||row.stepNumber!==row.currentStep||row.status!=="menunggu")return Response.json({error:"Tautan approval tidak lagi aktif."},{status:409});const data=await request.formData();const password=String(data.get("password")||"");if(!row.passwordHash||!await verifyPassword(password,row.passwordHash))return Response.json({error:"Password approval tidak sesuai."},{status:403});const action=String(data.get("action")||"");const note=String(data.get("note")||"").trim();if(!["approve","reject","revision"].includes(action))return Response.json({error:"Keputusan tidak dikenali."},{status:400});if(action!=="approve"&&!note)return Response.json({error:"Catatan wajib diisi."},{status:400});const useStored=data.get("useStored")==="true";const signature=data.get("signature");let signatureBytes:ArrayBuffer;if(useStored&&row.storedSignatureKey){const stored=await getBucket().get(row.storedSignatureKey);if(!stored)return Response.json({error:"Tanda tangan tersimpan tidak ditemukan."},{status:400});signatureBytes=await stored.arrayBuffer();}else{if(!(signature instanceof File)||signature.size<100)return Response.json({error:"Tanda tangan keputusan wajib dibubuhkan."},{status:400});signatureBytes=await signature.arrayBuffer();const storedKey=`users/${encodeURIComponent(row.approverEmail)}/signature.png`;await getBucket().put(storedKey,signatureBytes,{httpMetadata:{contentType:"image/png"}});await getD1().prepare("UPDATE users SET signature_key=?,updated_at=? WHERE lower(email)=lower(?)").bind(storedKey,new Date().toISOString(),row.approverEmail).run();}
  const now=new Date().toISOString();const approvalKey=`submissions/${row.submissionId}/approvals/${row.id}.png`;await getBucket().put(approvalKey,signatureBytes,{httpMetadata:{contentType:"image/png"}});const approvalStatus=action==="approve"?"disetujui":action==="reject"?"ditolak":"perlu_perbaikan";const db=getD1();await db.prepare("UPDATE approvals SET status=?,note=?,signature_key=?,acted_at=?,link_enabled=0 WHERE id=?").bind(approvalStatus,note,approvalKey,now,row.id).run();let nextStatus=approvalStatus;let nextStep=row.currentStep;let approvedAt:null|string=null;if(action==="approve"){const next=await db.prepare("SELECT step_number AS stepNumber FROM approvals WHERE submission_id=? AND step_number>? ORDER BY step_number LIMIT 1").bind(row.submissionId,row.currentStep).first<{stepNumber:number}>();if(next){nextStatus="menunggu_persetujuan";nextStep=next.stepNumber}else{nextStatus=row.stepNumber===1?"baru":"disetujui";if(nextStatus==="disetujui")approvedAt=now}}
  await db.prepare("UPDATE submissions SET status=?,current_step=?,approved_at=COALESCE(?,approved_at),updated_at=? WHERE id=?").bind(nextStatus,nextStep,approvedAt,now,row.submissionId).run();await writeAudit({submissionId:row.submissionId,actorEmail:row.approverEmail,actorName:row.approverName,action:`persetujuan_${action}`,detail:`${row.approverTitle}${note?`: ${note}`:""}`});return Response.json({ok:true,status:nextStatus})}
